 Read all the problem statements, notes carefully and scrape the required data using any web scraping tool of
your choice.
• You have to handle commonly occurring EXCEPTIONS by using exception handling programing. To get
information about selenium Exceptions. You may visit following links:
1. https://selenium-python.readthedocs.io/api.html
2. https://www.guru99.com/exception-handling-selenium.html
3. https://stackoverflow.com/questions/38022658/selenium-python-handling-no-such-element-
exception/38023345

1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: 
A)Rank
B) Name
C) Artist
D) Upload date
E) Views

In [120]:
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait
import regex as re

In [2]:
driver = webdriver.Chrome()

In [3]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [4]:
Name = []
Name_tag = driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"][1]//tbody/tr/td[1]')
for i in Name_tag:
    Name.append(i.text)

In [5]:
Name

['"Baby Shark Dance"[7]',
 '"Despacito"[10]',
 '"Johny Johny Yes Papa"[18]',
 '"Bath Song"[19]',
 '"See You Again"[20]',
 '"Shape of You"[25]',
 '"Wheels on the Bus"[28]',
 '"Phonics Song with Two Words"[29]',
 '"Uptown Funk"[30]',
 '"Gangnam Style"[31]',
 '"Learning Colors – Colorful Eggs on a Farm"[36]',
 '"Dame Tu Cosita"[37]',
 '"Axel F"[38]',
 '"Masha and the Bear – Recipe for Disaster"[39]',
 '"Baa Baa Black Sheep"[40]',
 '"Lakdi Ki Kathi"[41]',
 '"Sugar"[42]',
 '"Counting Stars"[43]',
 '"Roar"[44]',
 '"Waka Waka (This Time for Africa)"[45]',
 '"Shree Hanuman Chalisa"[46]',
 '"Humpty the train on a fruits ride"[47]',
 '"Sorry"[48]',
 '"Thinking Out Loud"[49]',
 '"Perfect"[50]',
 '"Dark Horse"[51]',
 '"Let Her Go"[52]',
 '"Faded"[53]',
 '"Girls Like You"[54]',
 '"Lean On"[55]']

In [6]:
Artist = []
Artist_tag = driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"][1]//tbody/tr/td[2]')
for i in Artist_tag:
    Artist.append(i.text)

In [7]:
Artist

["Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 "LooLoo Kids - Nursery Rhymes and Children's Songs",
 'Cocomelon - Nursery Rhymes',
 'Wiz Khalifa',
 'Ed Sheeran',
 'Cocomelon - Nursery Rhymes',
 'ChuChu TV Nursery Rhymes & Kids Songs',
 'Mark Ronson',
 'Psy',
 'Miroshka TV',
 'Ultra Records',
 'Crazy Frog',
 'Get Movies',
 'Cocomelon - Nursery Rhymes',
 'Jingle Toons',
 'Maroon 5',
 'OneRepublic',
 'Katy Perry',
 'Shakira',
 'T-Series Bhakti Sagar',
 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs',
 'Justin Bieber',
 'Ed Sheeran',
 'Ed Sheeran',
 'Katy Perry',
 'Passenger',
 'Alan Walker',
 'Maroon 5',
 'Major Lazer Official']

In [8]:
Views = []
Views_tag = driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"][1]//tbody/tr/td[3]')
for i in Views_tag:
    Views.append(i.text)

In [9]:
Views

['14.66',
 '8.47',
 '6.92',
 '6.75',
 '6.30',
 '6.28',
 '6.22',
 '5.84',
 '5.25',
 '5.20',
 '5.13',
 '4.68',
 '4.60',
 '4.60',
 '4.10',
 '4.07',
 '4.06',
 '4.03',
 '4.01',
 '3.96',
 '3.90',
 '3.84',
 '3.82',
 '3.78',
 '3.75',
 '3.74',
 '3.68',
 '3.65',
 '3.62',
 '3.62']

In [12]:
date = []
date_tag = driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"][1]//tbody/tr/td[4]')
for i in date_tag:
    date.append(i.text)

In [13]:
date

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'May 2, 2018',
 'April 6, 2015',
 'January 30, 2017',
 'May 24, 2018',
 'March 6, 2014',
 'November 19, 2014',
 'July 15, 2012',
 'February 27, 2018',
 'April 5, 2018',
 'June 16, 2009',
 'January 31, 2012',
 'June 25, 2018',
 'June 14, 2018',
 'January 14, 2015',
 'May 31, 2013',
 'September 5, 2013',
 'June 4, 2010',
 'May 10, 2011',
 'January 26, 2018',
 'October 22, 2015',
 'October 7, 2014',
 'November 9, 2017',
 'February 20, 2014',
 'July 25, 2012',
 'December 3, 2015',
 'May 31, 2018',
 'March 22, 2015']

## creating data frame Note: there is no need to scrape rank as data is alredy in order 1st ranked is 1st and last ranked is last

In [14]:
df1 = pd.DataFrame({"Name":Name,"Artist":Artist,"Upload date":date,"Views":Views})

In [15]:
df1

,Name,Artist,Upload date,Views
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.66
1,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.47
2,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.92
3,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.75
4,"""See You Again""[20]",Wiz Khalifa,"April 6, 2015",6.30
5,"""Shape of You""[25]",Ed Sheeran,"January 30, 2017",6.28
6,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.22
7,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.84
8,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.25
9,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.20
10,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.13
11,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.68
12,"""Axel F""[38]",Crazy Frog,"June 16, 2009",4.60
13,"""Masha and the Bear – Recipe for Disaster""[39]",Get Movies,"January 31, 2012",4.60
14,"""Baa Baa Black Sheep""[40]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.10
15,"""Lakdi Ki Kathi""[41]",Jingle Toons,"June 14, 2018",4.07
16,"""Sugar""[42]",Maroon 5,"January 14, 2015",4.06
17,"""Counting Stars""[43]",OneRepublic,"May 31, 2013",4.03
18,"""Roar""[44]",Katy Perry,"September 5, 2013",4.01
19,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.96
20,"""Shree Hanuman Chalisa""[46]",T-Series Bhakti Sagar,"May 10, 2011",3.90
21,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.84
22,"""Sorry""[48]",Justin Bieber,"October 22, 2015",3.82
23,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.78
24,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.75
25,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.74
26,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.68
27,"""Faded""[53]",Alan Walker,"December 3, 2015",3.65
28,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.62
29,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.62

### Scrape the details team India’s international fixtures from bcci.tv.
### Url = https://www.bcci.tv/.
### You need to find following details:
### A) Series
### B) Place
### C) Date
### D) Time
### Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [22]:
driver2 = webdriver.Chrome()

In [23]:
driver2.get("https://www.bcci.tv/")

In [24]:
international_result = driver2.find_element(By.XPATH,"/html/body/div[2]/ul/li/a[2]")
international_result.click()

In [25]:
filter_button = driver2.find_element(By.XPATH,"/html/body/section/div/div/div/div/div/div[2]/div[2]/div[2]/div/div")
filter_button.click()

In [26]:
india_filter = driver2.find_element(By.XPATH,"/html/body/section/div/div/div/div/div/div[3]/div/div[3]/div[1]/div[4]/div/label[22]/input")
india_filter.click()

In [27]:
apply_filter = driver2.find_element(By.XPATH,"/html/body/section/div/div/div/div/div/div[3]/div/div[3]/div[2]/div[2]")
apply_filter.click()

In [28]:
series = []
series_tag = driver2.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in series_tag:
    series.append(i.text)

In [29]:
series

['India Tour Of Zimbabwe T20I Series 2024',
 'India Tour Of Zimbabwe T20I Series 2024',
 'India Tour Of Zimbabwe T20I Series 2024',
 'India Tour Of Zimbabwe T20I Series 2024',
 'India Tour Of Zimbabwe T20I Series 2024']

In [32]:
Place = []
Place_tag = driver2.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
for i in Place_tag:
    Place.append(i.text)

In [33]:
Place

['Harare Sports Club,',
 'Harare Sports Club,',
 'Harare Sports Club,',
 'Harare Sports Club,',
 'Harare Sports Club,']

In [34]:
Date= []
Date_tag = driver2.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in Date_tag:
    Date.append(i.text)

In [36]:
Date

['6 Jul', '7 Jul', '10 Jul', '13 Jul', '14 Jul']

In [37]:
Time= []
Time_tag = driver2.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in Time_tag:
    Time.append(i.text)

In [38]:
Time

['13:00 CEST', '13:00 CEST', '13:00 CEST', '13:00 CEST', '13:00 CEST']

### 3. Scrape the details of State-wise GDP of India from statisticstime.com.
### Url = http://statisticstimes.com/
### You have to find following details: A) Rank
### B) State
### C) GSDP(18-19)- at current prices
### D) GSDP(19-20)- at current prices
### E) Share(18-19)
### F) GDP ($ billion)Note: - From statisticstimes home page you have to reach to economy page through code.

In [52]:
driver3 = webdriver.Chrome()

In [53]:
driver3.get("https://statisticstimes.com/")

In [54]:
economy_button = driver3.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/button")
economy_button.click()

In [55]:
india_button = driver3.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
india_button.click()

In [56]:
gdp_button = driver3.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
gdp_button.click()

# note: i am scraping data for 21-22-23 there is no data for 18-19-20

In [58]:
State_Rank = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[1]'):
        State_Rank.append(i.text)
except NoSuchElementException as e:
        State_Rank.append("-")

In [59]:
State_Rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [62]:
State = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[2]'):
        State.append(i.text)
except NoSuchElementException as e:
        State.append("-")

In [63]:
State

['Maharashtra',
 'Tamil Nadu',
 'Karnataka',
 'Uttar Pradesh',
 'Gujarat',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Odisha',
 'Bihar',
 'Punjab',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Arunachal Pradesh',
 'Nagaland',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [64]:
GSDP23_24 = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[3]'):
        GSDP23_24.append(i.text)
except NoSuchElementException as e:
        GSDP23_24.append("-")

In [65]:
GSDP23_24

['-',
 '2,700,109',
 '2,500,733',
 '2,547,861',
 '-',
 '1,700,939',
 '1,524,030',
 '1,439,674',
 '1,463,960',
 '1,363,327',
 '-',
 '1,107,746',
 '1,095,535',
 '832,790',
 '-',
 '736,423',
 '565,401',
 '505,887',
 '-',
 '346,206',
 '246,465',
 '207,430',
 '-',
 '-',
 '-',
 '-',
 '47,381',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-']

In [66]:
GSDP22_23 = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[4]'):
        GSDP22_23.append(i.text)
except NoSuchElementException as e:
        GSDP22_23.append("-")

In [67]:
GSDP22_23

['-',
 '2,364,514',
 '2,269,995',
 '2,258,040',
 '2,230,609',
 '1,531,758',
 '1,365,849',
 '1,303,524',
 '1,308,034',
 '1,246,471',
 '1,046,188',
 '1,014,688',
 '984,055',
 '753,177',
 '751,396',
 '676,164',
 '493,167',
 '464,399',
 '393,722',
 '303,781',
 '224,226',
 '191,728',
 '93,672',
 '72,636',
 '54,285',
 '49,643',
 '42,697',
 '42,756',
 '-',
 '39,630',
 '35,643',
 '-',
 '-']

In [68]:
GSDP21_22 = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[5]'):
        GSDP21_22.append(i.text)
except NoSuchElementException as e:
        GSDP21_22.append("-")

In [69]:
GSDP21_22

['3,108,022',
 '2,071,286',
 '1,978,094',
 '1,975,595',
 '1,928,683',
 '1,329,238',
 '1,193,489',
 '1,148,471',
 '1,124,204',
 '1,092,964',
 '934,542',
 '881,336',
 '868,905',
 '662,886',
 '650,302',
 '617,192',
 '411,454',
 '410,525',
 '358,863',
 '267,143',
 '193,352',
 '172,162',
 '84,266',
 '62,550',
 '46,096',
 '43,810',
 '38,785',
 '37,557',
 '36,594',
 '34,775',
 '31,038',
 '27,824',
 '10,371']

In [72]:
share21_22 = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[6]'):
        share21_22.append(i.text)
except NoSuchElementException as e:
        share21_22.append("-")

In [73]:
share21_22

['13.17%',
 '8.78%',
 '8.38%',
 '8.37%',
 '8.17%',
 '5.63%',
 '5.06%',
 '4.87%',
 '4.76%',
 '4.63%',
 '3.96%',
 '3.73%',
 '3.68%',
 '2.81%',
 '2.76%',
 '2.62%',
 '1.74%',
 '1.74%',
 '1.52%',
 '1.13%',
 '0.82%',
 '0.73%',
 '0.36%',
 '0.27%',
 '0.20%',
 '0.19%',
 '0.16%',
 '0.16%',
 '0.16%',
 '0.15%',
 '0.13%',
 '0.12%',
 '0.04%']

In [74]:
gdp_billion = []
try:
    for i in driver3.find_elements(By.XPATH,'//div[5]//div//table[1][@class="display dataTable"]/tbody[1]/tr/td[7]'):
        gdp_billion.append(i.text)
except NoSuchElementException as e:
        gdp_billion.append("-")

In [75]:
gdp_billion

['414.928',
 '276.522',
 '264.080',
 '263.747',
 '257.484',
 '177.456',
 '159.334',
 '153.324',
 '150.084',
 '145.913',
 '124.764',
 '117.660',
 '116.001',
 '88.497',
 '86.817',
 '82.397',
 '54.930',
 '54.806',
 '47.909',
 '35.664',
 '25.813',
 '22.984',
 '11.250',
 '8.351',
 '6.154',
 '5.849',
 '5.178',
 '5.014',
 '4.885',
 '4.643',
 '4.144',
 '3.715',
 '1.385']

In [78]:
df3 = pd.DataFrame({"state Rank":State_Rank,"State":State,"GSDP23_24":GSDP23_24,"GSDP(23-22)":GSDP22_23,"GSDP(21-22)":GSDP21_22,"Share(21-22)":share21_22,"GDP_billion":gdp_billion})

In [79]:
df3

,state Rank,State,GSDP23_24,GSDP(23-22),GSDP(21-22),Share(21-22),GDP_billion
0,1,Maharashtra,-,-,"3,108,022",13.17%,414.928
1,2,Tamil Nadu,"2,700,109","2,364,514","2,071,286",8.78%,276.522
2,3,Karnataka,"2,500,733","2,269,995","1,978,094",8.38%,264.080
3,4,Uttar Pradesh,"2,547,861","2,258,040","1,975,595",8.37%,263.747
4,5,Gujarat,-,"2,230,609","1,928,683",8.17%,257.484
5,6,West Bengal,"1,700,939","1,531,758","1,329,238",5.63%,177.456
6,7,Rajasthan,"1,524,030","1,365,849","1,193,489",5.06%,159.334
7,8,Andhra Pradesh,"1,439,674","1,303,524","1,148,471",4.87%,153.324
8,9,Telangana,"1,463,960","1,308,034","1,124,204",4.76%,150.084
9,10,Madhya Pradesh,"1,363,327","1,246,471","1,092,964",4.63%,145.913
10,11,Kerala,-,"1,046,188","934,542",3.96%,124.764
11,12,Delhi,"1,107,746","1,014,688","881,336",3.73%,117.660
12,13,Haryana,"1,095,535","984,055","868,905",3.68%,116.001
13,14,Odisha,"832,790","753,177","662,886",2.81%,88.497
14,15,Bihar,-,"751,396","650,302",2.76%,86.817
15,16,Punjab,"736,423","676,164","617,192",2.62%,82.397
16,17,Assam,"565,401","493,167","411,454",1.74%,54.930
17,18,Chhattisgarh,"505,887","464,399","410,525",1.74%,54.806
18,19,Jharkhand,-,"393,722","358,863",1.52%,47.909
19,20,Uttarakhand,"346,206","303,781","267,143",1.13%,35.664
20,21,Jammu & Kashmir,"246,465","224,226","193,352",0.82%,25.813
21,22,Himachal Pradesh,"207,430","191,728","172,162",0.73%,22.984
22,23,Goa,-,"93,672","84,266",0.36%,11.250
23,24,Tripura,-,"72,636","62,550",0.27%,8.351
24,25,Chandigarh,-,"54,285","46,096",0.20%,6.154
25,26,Puducherry,-,"49,643","43,810",0.19%,5.849
26,27,Meghalaya,"47,381","42,697","38,785",0.16%,5.178
27,28,Sikkim,-,"42,756","37,557",0.16%,5.014
28,29,Manipur,-,-,"36,594",0.16%,4.885
29,30,Arunachal Pradesh,-,"39,630","34,775",0.15%,4.643
30,31,Nagaland,-,"35,643","31,038",0.13%,4.144
31,32,Mizoram,-,-,"27,824",0.12%,3.715
32,33,Andaman & Nicobar Islands,-,-,"10,371",0.04%,1.385

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [121]:
driver4 = webdriver.Chrome()

In [122]:
driver4.get("https://github.com/trending")

In [123]:
repo_url =[]
for i in driver4.find_elements(By.XPATH,'//a[@ class="Link"]'):
    repo_url.append(i.get_attribute("href"))

In [85]:
repo_url

['https://github.com/microsoft/generative-ai-for-beginners',
 'https://github.com/microsoft/graphrag',
 'https://github.com/fishaudio/fish-speech',
 'https://github.com/joschan21/digitalhippo',
 'https://github.com/Azure-Samples/graphrag-accelerator',
 'https://github.com/mindsdb/mindsdb',
 'https://github.com/folke/tokyonight.nvim',
 'https://github.com/Asabeneh/30-Days-Of-Python',
 'https://github.com/public-apis/public-apis',
 'https://github.com/immich-app/immich',
 'https://github.com/facebook/react-native',
 'https://github.com/laravel/laravel',
 'https://github.com/restic/restic',
 'https://github.com/vercel/next.js',
 'https://github.com/BLAKE3-team/BLAKE3']

In [90]:
title = []
for a in repo_url:
    driver4.get(a)
    try:
        title_tag=driver4.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/main/div/div[1]/div[1]/div/strong/a")
        title.append(title_tag.text)
    except NoSuchElementException as e:
        title.append("-")

In [91]:
title

['generative-ai-for-beginners',
 'graphrag',
 'fish-speech',
 'digitalhippo',
 'graphrag-accelerator',
 'mindsdb',
 'tokyonight.nvim',
 '30-Days-Of-Python',
 'public-apis',
 'immich',
 'react-native',
 'laravel',
 'restic',
 'next.js',
 'BLAKE3']

In [92]:
description = []
for a in repo_url:
    driver4.get(a)
    try:
        description_tag=driver4.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[1]/div/div/p")
        description.append(description_tag.text)
    except NoSuchElementException as e:
        description.append("-")

In [93]:
description

['18 Lessons, Get Started Building with Generative AI 🔗 https://microsoft.github.io/generative-ai-for-beginners/',
 'A modular graph-based Retrieval-Augmented Generation (RAG) system',
 'Brand new TTS solution',
 'A Modern Fullstack E-Commerce Marketplace for Digital Products',
 'One-click deploy of a Knowledge Graph powered RAG (GraphRAG) in Azure',
 'The platform for building AI from enterprise data',
 '🏙 A clean, dark Neovim theme written in Lua, with support for lsp, treesitter and lots of plugins. Includes additional themes for Kitty, Alacritty, iTerm and Fish.',
 '30 days of Python programming challenge is a step-by-step guide to learn the Python programming language in 30 days. This challenge may take more than100 days, follow your own pace. These videos may help too: https://www.youtube.com/channel/UC7PNRuno1rzYPb1xLa4yktw',
 'A collective list of free APIs',
 'High performance self-hosted photo and video management solution.',
 'A framework for building native applications using React',
 'Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation for your next big idea — freeing you to create without sweating the small things.',
 'Fast, secure, efficient backup program',
 'The React Framework',
 'the official Rust and C implementations of the BLAKE3 cryptographic hash function']

In [94]:
count = []
for a in repo_url:
    driver4.get(a)
    try:
        count_tag=driver4.find_element(By.XPATH,"/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[3]/div/h2/a/span")
        count.append(count_tag.text)
    except NoSuchElementException as e:
        count.append("-")

In [95]:
count

['77',
 '',
 '-',
 '',
 '-',
 '',
 '-',
 '',
 '1,263',
 '7',
 '',
 '-',
 '-',
 '3m',
 '62.2k']

In [130]:
language = []
counter = 0
for a in repo_url:
    driver4.get(a)
    try:
        language_tag=driver4.find_elements(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]')
        language.append([i.text for i in language_tag])
    except NoSuchElementException as e:
        language.append("-")

In [131]:
language

[['Jupyter Notebook', 'Python', 'TypeScript', 'JavaScript', 'Other'],
 ['Python',
  'Jupyter Notebook',
  'Nunjucks',
  'Jinja',
  'CSS',
  'JavaScript',
  'Shell'],
 ['Python', 'Batchfile', 'Other'],
 ['TypeScript', 'CSS', 'JavaScript'],
 ['Python', 'Bicep', 'Jupyter Notebook', 'Shell', 'Smarty', 'Dockerfile'],
 ['Python', 'Other'],
 ['Lua', 'Vim Script', 'Shell', 'JavaScript', 'C'],
 ['Python', 'CSS', 'HTML'],
 ['Python', 'Shell'],
 ['TypeScript', 'Dart', 'Svelte', 'Python', 'Swift', 'Kotlin', 'Other'],
 ['C++',
  'Java',
  'JavaScript',
  'Objective-C++',
  'Objective-C',
  'Kotlin',
  'Other'],
 ['PHP', 'Blade', 'JavaScript'],
 ['Go', 'Other'],
 ['JavaScript', 'TypeScript', 'Rust', 'MDX', 'CSS', 'Shell'],
 ['Assembly', 'Rust', 'C', 'Other']]

In [132]:
len(language)

15

In [133]:
len(count)

15

In [134]:
df4 = pd.DataFrame({"Repository title":title,"Repository description":description,"Contributors count":count,"Language used":language})

In [135]:
df4

,Repository title,Repository description,Contributors count,Language used
0,generative-ai-for-beginners,"18 Lessons, Get Started Building with Generati...",77,"[Jupyter Notebook, Python, TypeScript, JavaScr..."
1,graphrag,A modular graph-based Retrieval-Augmented Gene...,,"[Python, Jupyter Notebook, Nunjucks, Jinja, CS..."
2,fish-speech,Brand new TTS solution,-,"[Python, Batchfile, Other]"
3,digitalhippo,A Modern Fullstack E-Commerce Marketplace for ...,,"[TypeScript, CSS, JavaScript]"
4,graphrag-accelerator,One-click deploy of a Knowledge Graph powered ...,-,"[Python, Bicep, Jupyter Notebook, Shell, Smart..."
5,mindsdb,The platform for building AI from enterprise data,,"[Python, Other]"
6,tokyonight.nvim,"🏙 A clean, dark Neovim theme written in Lua, w...",-,"[Lua, Vim Script, Shell, JavaScript, C]"
7,30-Days-Of-Python,30 days of Python programming challenge is a s...,,"[Python, CSS, HTML]"
8,public-apis,A collective list of free APIs,"1,263","[Python, Shell]"
9,immich,High performance self-hosted photo and video m...,7,"[TypeScript, Dart, Svelte, Python, Swift, Kotl..."
10,react-native,A framework for building native applications u...,,"[C++, Java, JavaScript, Objective-C++, Objecti..."
11,laravel,Laravel is a web application framework with ex...,-,"[PHP, Blade, JavaScript]"
12,restic,"Fast, secure, efficient backup program",-,"[Go, Other]"
13,next.js,The React Framework,3m,"[JavaScript, TypeScript, Rust, MDX, CSS, Shell]"
14,BLAKE3,the official Rust and C implementations of the...,62.2k,"[Assembly, Rust, C, Other]"

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [136]:
driver5 = webdriver.Chrome()

In [137]:
driver5.get("https://www.billboard.com/")

In [138]:
charts_button = driver5.find_element(By.XPATH,"/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a")
charts_button.click()

In [139]:
hot_button = driver5.find_element(By.XPATH,"/html/body/div[3]/header/div/div[3]/div/nav/ul/li[1]/a")
hot_button.click()

In [140]:
song_name = []
try:
    for i in driver5.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/h3'):
        song_name.append(i.text)
except NoSuchElementException as e:
        song_name.append("-")

In [141]:
song_name

['I Had Some Help',
 'A Bar Song (Tipsy)',
 'Not Like Us',
 'Espresso',
 'Please Please Please',
 'Million Dollar Baby',
 'Too Sweet',
 'Beautiful Things',
 'Lose Control',
 'Birds Of A Feather',
 'Good Luck, Babe!',
 'Pour Me A Drink',
 'Pink Skies',
 'Like That',
 'Cowgirls',
 'Houdini',
 'Fortnight',
 'Saturn',
 'Austin',
 'I Remember Everything',
 'Whiskey Whiskey',
 'Feather',
 "We Can't Be Friends (Wait For Your Love)",
 'Miles On It',
 'Lunch',
 'Wanna Be',
 'Lovin On Me',
 'High Road',
 'The Boy Is Mine',
 'Stick Season',
 'I Am Not Okay',
 'Yeah Glo!',
 'Gata Only',
 'Si Antes Te Hubiera Conocido',
 'Devil Is A Lie',
 'Us.',
 "Ain't No Love In Oklahoma",
 'Hot To Go!',
 'BAND4BAND',
 'End Of Beginning',
 'Slow It Down',
 'Get It Sexyy',
 'Where It Ends',
 'Euphoria',
 'Bulletproof',
 'Red Wine Supernova',
 'TGIF',
 'Greedy',
 'Stargazing',
 'I Can Do It With A Broken Heart',
 'Dirt Cheap',
 'Whatever She Wants',
 'You Look Like You Love Me',
 'Chihiro',
 'Type Shit',
 'One Of Wun',
 'Parking Lot',
 'I Like The Way You Kiss Me',
 'Illusion',
 'Close To You',
 'Nasty',
 'We Ride',
 'Girl, So Confusing',
 'Sweet Dreams',
 "Wind Up Missin' You",
 'Pink Pony Club',
 'U My Everything',
 'Down Bad',
 'Reloj',
 'Kehlani',
 'Remember Him That Way',
 'After Hours',
 'Si No Quieres No',
 'Scared To Start',
 'Wildflower',
 'Nights Like This',
 'Wine Into Whiskey',
 'The Door',
 '360',
 "Think I'm In Love With You",
 'feelslikeimfallinginlove',
 'Casual',
 'Beautiful As You',
 "L'amour De Ma Vie",
 'Let Your Boys Be Country',
 "Who's Afraid Of Little Old Me?",
 'Halfway To Hell',
 'Belong Together',
 'Hang Tight Honey',
 "Texas Hold 'Em",
 'Vino Tinto',
 "We Don't Fight Anymore",
 'Hell N Back',
 'Risk',
 'Chevrolet',
 'The Man He Sees In Me',
 'Brother Stone',
 'Guilty As Sin?',
 'La Patrulla',
 'Bandit']

In [142]:
Artist_name = []
try:
    for i in driver5.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/span'):
        Artist_name.append(i.text)
except NoSuchElementException as e:
        Artist_name.append("-")

In [143]:
len(Artist_name)

100

In [144]:
Artist_name

['Post Malone Featuring Morgan Wallen',
 'Shaboozey',
 'Kendrick Lamar',
 'Sabrina Carpenter',
 'Sabrina Carpenter',
 'Tommy Richman',
 'Hozier',
 'Benson Boone',
 'Teddy Swims',
 'Billie Eilish',
 'Chappell Roan',
 'Post Malone Featuring Blake Shelton',
 'Zach Bryan',
 'Future, Metro Boomin & Kendrick Lamar',
 'Morgan Wallen Featuring ERNEST',
 'Eminem',
 'Taylor Swift Featuring Post Malone',
 'SZA',
 'Dasha',
 'Zach Bryan Featuring Kacey Musgraves',
 'Moneybagg Yo Featuring Morgan Wallen',
 'Sabrina Carpenter',
 'Ariana Grande',
 'Marshmello & Kane Brown',
 'Billie Eilish',
 'GloRilla & Megan Thee Stallion',
 'Jack Harlow',
 'Koe Wetzel & Jessie Murph',
 'Ariana Grande',
 'Noah Kahan',
 'Jelly Roll',
 'GloRilla',
 'FloyyMenor X Cris Mj',
 'Karol G',
 'Tommy Richman',
 'Gracie Abrams Featuring Taylor Swift',
 'Luke Combs',
 'Chappell Roan',
 'Central Cee & Lil Baby',
 'Djo',
 'Benson Boone',
 'Sexyy Red',
 'Bailey Zimmerman',
 'Kendrick Lamar',
 'Nate Smith',
 'Chappell Roan',
 'GloRilla',
 'Tate McRae',
 'Myles Smith',
 'Taylor Swift',
 'Cody Johnson',
 'Bryson Tiller',
 'Ella Langley Featuring Riley Green',
 'Billie Eilish',
 'Future, Metro Boomin, Travis Scott & Playboi Carti',
 'Gunna',
 'Mustard & Travis Scott',
 'Artemas',
 'Dua Lipa',
 'Gracie Abrams',
 'Tinashe',
 'Bryan Martin',
 'Charli XCX With Lorde',
 'Koe Wetzel',
 'Tucker Wetmore',
 'Chappell Roan',
 'Sexyy Red & Drake',
 'Taylor Swift',
 'Peso Pluma & Ivan Cornejo',
 'Jordan Adetunji',
 'Luke Combs',
 'Kehlani',
 'Luis R Conriquez x Neton Vega',
 'Michael Marcagi',
 'Billie Eilish',
 'The Kid LAROI',
 'Tucker Wetmore',
 'Teddy Swims',
 'Charli XCX',
 'Chris Stapleton',
 'Coldplay',
 'Chappell Roan',
 'Thomas Rhett',
 'Billie Eilish',
 'Jason Aldean',
 'Taylor Swift',
 'Jelly Roll',
 'Mark Ambor',
 'Lainey Wilson',
 'Beyonce',
 'Peso Pluma, Natanael Cano & Gabito Ballesteros',
 'Carly Pearce Featuring Chris Stapleton',
 'Bakar Featuring Summer Walker',
 'Gracie Abrams',
 'Dustin Lynch Featuring Jelly Roll',
 'Luke Combs',
 'Don Toliver Featuring Kodak Black',
 'Taylor Swift',
 'Peso Pluma & Neton Vega',
 'Don Toliver']

In [145]:
lastweek_rank = []
try:
    for i in driver5.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[4]'):
        lastweek_rank.append(i.text)
except NoSuchElementException as e:
        lastweek_rank.append("-")

In [146]:
lastweek_rank

['2',
 '3',
 '6',
 '4',
 '1',
 '5',
 '7',
 '8',
 '9',
 '10',
 '16',
 '-',
 '11',
 '14',
 '15',
 '12',
 '13',
 '17',
 '20',
 '22',
 '21',
 '23',
 '19',
 '24',
 '18',
 '25',
 '26',
 '27',
 '74',
 '28',
 '30',
 '32',
 '31',
 '-',
 '47',
 '-',
 '33',
 '55',
 '29',
 '37',
 '34',
 '38',
 '43',
 '52',
 '40',
 '54',
 '-',
 '41',
 '44',
 '45',
 '53',
 '48',
 '-',
 '36',
 '51',
 '50',
 '-',
 '46',
 '60',
 '69',
 '62',
 '63',
 '-',
 '49',
 '67',
 '90',
 '59',
 '64',
 '-',
 '-',
 '35',
 '81',
 '65',
 '72',
 '57',
 '-',
 '68',
 '76',
 '82',
 '66',
 '-',
 '-',
 '85',
 '70',
 '94',
 '83',
 '75',
 '79',
 '-',
 '77',
 '-',
 '-',
 '87',
 '-',
 '100',
 '39',
 '61',
 '88',
 '-',
 '73']

In [147]:
Peak_rank = []
try:
    for i in driver5.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[5]'):
        Peak_rank.append(i.text)
except NoSuchElementException as e:
        Peak_rank.append("-")

In [149]:
Peak_rank

['1',
 '2',
 '1',
 '3',
 '1',
 '2',
 '1',
 '2',
 '1',
 '9',
 '11',
 '12',
 '6',
 '1',
 '15',
 '2',
 '1',
 '6',
 '19',
 '1',
 '21',
 '21',
 '1',
 '21',
 '5',
 '11',
 '1',
 '27',
 '16',
 '9',
 '30',
 '28',
 '27',
 '34',
 '35',
 '36',
 '23',
 '38',
 '18',
 '11',
 '34',
 '20',
 '32',
 '3',
 '37',
 '46',
 '47',
 '3',
 '41',
 '3',
 '51',
 '19',
 '53',
 '12',
 '2',
 '26',
 '57',
 '12',
 '43',
 '49',
 '61',
 '61',
 '63',
 '35',
 '63',
 '66',
 '44',
 '2',
 '69',
 '70',
 '35',
 '72',
 '53',
 '54',
 '17',
 '76',
 '68',
 '76',
 '73',
 '49',
 '81',
 '82',
 '83',
 '22',
 '85',
 '9',
 '48',
 '74',
 '89',
 '1',
 '91',
 '67',
 '53',
 '94',
 '95',
 '39',
 '61',
 '10',
 '99',
 '38']

In [150]:
Weeksonboard = []
try:
    for i in driver5.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[6]'):
        Weeksonboard.append(i.text)
except NoSuchElementException as e:
        Weeksonboard.append("-")

In [151]:
Weeksonboard

['7',
 '11',
 '8',
 '11',
 '3',
 '9',
 '14',
 '23',
 '46',
 '6',
 '12',
 '1',
 '5',
 '14',
 '28',
 '4',
 '10',
 '18',
 '16',
 '44',
 '2',
 '30',
 '16',
 '8',
 '6',
 '12',
 '33',
 '3',
 '8',
 '39',
 '2',
 '20',
 '15',
 '1',
 '2',
 '1',
 '6',
 '4',
 '5',
 '19',
 '14',
 '15',
 '26',
 '9',
 '12',
 '4',
 '1',
 '41',
 '7',
 '10',
 '10',
 '19',
 '1',
 '6',
 '14',
 '7',
 '1',
 '14',
 '11',
 '3',
 '4',
 '12',
 '1',
 '6',
 '13',
 '2',
 '5',
 '10',
 '1',
 '1',
 '2',
 '5',
 '8',
 '19',
 '6',
 '1',
 '14',
 '4',
 '3',
 '8',
 '1',
 '1',
 '3',
 '6',
 '3',
 '10',
 '12',
 '9',
 '2',
 '20',
 '1',
 '12',
 '12',
 '1',
 '2',
 '3',
 '2',
 '10',
 '1',
 '18']

In [152]:
df5 = pd.DataFrame({"Song name":song_name,"Artist name":Artist_name,"Last week rank":lastweek_rank,"Peak rank":Peak_rank,"Weeks on board":Weeksonboard})

In [153]:
df5

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,I Had Some Help,Post Malone Featuring Morgan Wallen,2,1,7
1,A Bar Song (Tipsy),Shaboozey,3,2,11
2,Not Like Us,Kendrick Lamar,6,1,8
3,Espresso,Sabrina Carpenter,4,3,11
4,Please Please Please,Sabrina Carpenter,1,1,3
...,...,...,...,...,...
95,The Man He Sees In Me,Luke Combs,39,39,3
96,Brother Stone,Don Toliver Featuring Kodak Black,61,61,2
97,Guilty As Sin?,Taylor Swift,88,10,10
98,La Patrulla,Peso Pluma & Neton Vega,-,99,1
99,Bandit,Don Toliver,73,38,18

6. Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [154]:
driver6 = webdriver.Chrome()

In [155]:
driver6.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [156]:
Book_name = []
try:
    for i in driver6.find_elements(By.XPATH,'//td[2][@class="left"]'):
        Book_name.append(i.text)
except NoSuchElementException as e:
        Book_name.append("-")

In [157]:
Book_name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [158]:
Author_name = []
try:
    for i in driver6.find_elements(By.XPATH,'//td[3][@class="left"]'):
        Author_name.append(i.text)
except NoSuchElementException as e:
        Author_name.append("-")
Author_name

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [160]:
Volume_sold = []
try:
    for i in driver6.find_elements(By.XPATH,'//td[4][@class="left"]'):
        Volume_sold.append(i.text)
except NoSuchElementException as e:
        Volume_sold.append("-")
Volume_sold

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [161]:
Publisher = []
try:
    for i in driver6.find_elements(By.XPATH,'//td[5][@class="left"]'):
        Publisher.append(i.text)
except NoSuchElementException as e:
        Publisher.append("-")
Publisher

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [163]:
Genre = []
try:
    for i in driver6.find_elements(By.XPATH,'//td[@class="last left"]'):
        Genre.append(i.text)
except NoSuchElementException as e:
        Genre.append("-")
Genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [164]:
df6 = pd.DataFrame({"Book name":Book_name,"Author name":Author_name,"Volumes sold":Volume_sold,"Publisher":Publisher,"Genre":Genre})

In [165]:
df6

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You have
to find the following details:
    
A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [166]:
driver7 = webdriver.Chrome()

In [167]:
driver7.get("https://www.imdb.com/chart/tvmeter/?ref_=nv_tvv_mptv")

In [168]:
Show_name = []
try:
    for i in driver7.find_elements(By.XPATH,'//div[@class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-b189961a-9 iALATN cli-title"]'):
        Show_name.append(i.text)
except NoSuchElementException as e:
        Show_name.append("-")
Show_name

['The Boys',
 'House of the Dragon',
 'The Bear',
 'The Acolyte',
 'Bridgerton',
 'Presumed Innocent',
 'Game of Thrones',
 'Dark Matter',
 'Your Honor',
 'Dexter',
 'My Lady Jane',
 'Doctor Who',
 'Criminal Minds',
 'Fallout',
 'Breaking Bad',
 'Eric',
 'Suits',
 'Stranger Things',
 'Yellowstone',
 "Grey's Anatomy",
 'Mayor of Kingstown',
 'The Sopranos',
 'Demon Slayer: Kimetsu no Yaiba',
 'The Walking Dead',
 'Supernatural',
 'Doctor Who',
 'The Rookie',
 'Shōgun',
 'The Penguin',
 'Rick and Morty',
 'Young Sheldon',
 'Gen V',
 'Law & Order: Special Victims Unit',
 'True Detective',
 'NCIS: Naval Criminal Investigative Service',
 'Supacell',
 'House M.D.',
 'Shameless',
 'The Office',
 'Evil',
 'Sweet Tooth',
 'Smiling Friends',
 'From',
 'The Big Bang Theory',
 'The Gentlemen',
 'Better Call Saul',
 'Attack on Titan',
 'Psych',
 'The Last of Us',
 "That '90s Show",
 'Outlander',
 '3 Body Problem',
 'Modern Family',
 'Interview with the Vampire',
 'Peaky Blinders',
 'Friends',
 'How I Met Your Mother',
 'Severance',
 '9-1-1',
 'Orphan Black: Echoes',
 'Under the Bridge',
 'Midsomer Murders',
 'Sex Education',
 'Hacks',
 'Succession',
 'Black Mirror',
 'Vikings',
 'One Piece',
 'Ted Lasso',
 'Monk',
 'Fargo',
 'Lost',
 'American Horror Story',
 'Bones',
 'Euphoria',
 'White Collar',
 'The Chosen',
 'Baby Reindeer',
 'Brooklyn Nine-Nine',
 'Clanes',
 'Shoresy',
 'The Crown',
 "It's Always Sunny in Philadelphia",
 'The Wire',
 'Batman: Caped Crusader',
 'Queen Charlotte: A Bridgerton Story',
 'The Lord of the Rings: The Rings of Power',
 'The White Lotus',
 'Tracker',
 'Reacher',
 'The Good Doctor',
 'Resident Alien',
 'Band of Brothers',
 'Sons of Anarchy',
 'Land of Women',
 'The X Files',
 'Power Book II: Ghost',
 'Tulsa King',
 'Kaiju No. 8',
 'The Witcher']

In [169]:
len(Show_name)

100

In [170]:
span = []
try:
    for i in driver7.find_elements(By.XPATH,'//span[1][@class="sc-b189961a-8 kLaxqf cli-title-metadata-item"]'):
        span.append(i.text)
except NoSuchElementException as e:
        span.append("-")
span

['2019–',
 '2022–',
 '2022–',
 '2024–',
 '2020–',
 '2024',
 '2011–2019',
 '2024–',
 '2020–2023',
 '2006–2013',
 '2024–',
 '2023–',
 '2005–',
 '2024–',
 '2008–2013',
 '2024',
 '2011–2019',
 '2016–2025',
 '2018–',
 '2005–',
 '2021–',
 '1999–2007',
 '2019–',
 '2010–2022',
 '2005–2020',
 '2005–2022',
 '2018–',
 '2024–2026',
 '2024–',
 '2013–',
 '2017–2024',
 '2023–',
 '1999–',
 '2014–',
 '2003–',
 '2024–',
 '2004–2012',
 '2011–2021',
 '2005–2013',
 '2019–2024',
 '2021–2024',
 '2020–',
 '2022–',
 '2007–2019',
 '2024',
 '2015–2022',
 '2013–2023',
 '2006–2014',
 '2023–',
 '2023–',
 '2014–',
 '2024–',
 '2009–2020',
 '2022–',
 '2013–2022',
 '1994–2004',
 '2005–2014',
 '2022–',
 '2018–',
 '2023–',
 '2024',
 '1997–',
 '2019–2023',
 '2021–',
 '2018–2023',
 '2011–',
 '2013–2020',
 '1999–',
 '2020–2023',
 '2002–2009',
 '2014–2024',
 '2004–2010',
 '2011–',
 '2005–2017',
 '2019–',
 '2009–2014',
 '2017–',
 '2024',
 '2013–2021',
 '2024',
 '2022–',
 '2016–2023',
 '2005–',
 '2002–2008',
 '2024–',
 '2023',
 '2022–',
 '2021–2025',
 '2024–',
 '2022–',
 '2017–2024',
 '2021–',
 '2001',
 '2008–2014',
 '2024',
 '1993–2018',
 '2020–2024',
 '2022–',
 '2024–',
 '2019–']

In [171]:
genre = []
try:
    for i in driver7.find_elements(By.XPATH,'//span[@class="sc-b189961a-3 hidKPx cli-title-type-data"]'):
        genre.append(i.text)
except NoSuchElementException as e:
        genre.append("-")
genre

['TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Mini Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series',
 'TV Series']

In [172]:
Run_time = []
try:
    for i in driver7.find_elements(By.XPATH,'//span[2][@class="sc-b189961a-8 kLaxqf cli-title-metadata-item"]'):
        Run_time.append(i.text)
except NoSuchElementException as e:
        Run_time.append("-")
Run_time

['33 eps',
 '20 eps',
 '29 eps',
 '8 eps',
 '25 eps',
 '8 eps',
 '74 eps',
 '9 eps',
 '20 eps',
 '96 eps',
 '8 eps',
 '16 eps',
 '345 eps',
 '9 eps',
 '62 eps',
 '6 eps',
 '134 eps',
 '42 eps',
 '53 eps',
 '431 eps',
 '30 eps',
 '86 eps',
 '69 eps',
 '177 eps',
 '327 eps',
 '175 eps',
 '109 eps',
 '12 eps',
 '8 eps',
 '74 eps',
 '141 eps',
 '10 eps',
 '552 eps',
 '31 eps',
 '468 eps',
 '6 eps',
 '176 eps',
 '134 eps',
 '188 eps',
 '50 eps',
 '24 eps',
 '21 eps',
 '30 eps',
 '280 eps',
 '8 eps',
 '63 eps',
 '98 eps',
 '121 eps',
 '16 eps',
 '19 eps',
 '101 eps',
 '10 eps',
 '250 eps',
 '16 eps',
 '36 eps',
 '234 eps',
 '208 eps',
 '19 eps',
 '107 eps',
 '10 eps',
 '8 eps',
 '140 eps',
 '32 eps',
 '28 eps',
 '39 eps',
 '33 eps',
 '93 eps',
 '1124 eps',
 '34 eps',
 '124 eps',
 '51 eps',
 '121 eps',
 '133 eps',
 '245 eps',
 '19 eps',
 '81 eps',
 '35 eps',
 '7 eps',
 '153 eps',
 '7 eps',
 '18 eps',
 '60 eps',
 '172 eps',
 '60 eps',
 '11 eps',
 '6 eps',
 '17 eps',
 '14 eps',
 '14 eps',
 '17 eps',
 '126 eps',
 '35 eps',
 '10 eps',
 '92 eps',
 '6 eps',
 '217 eps',
 '36 eps',
 '19 eps',
 '12 eps',
 '26 eps']

In [173]:
vote = []
try:
    for i in driver7.find_elements(By.XPATH,'//span[@class="ipc-rating-star--voteCount"]'):
        vote.append(i.text)
except NoSuchElementException as e:
        vote.append("-")
vote

[' (682K)',
 ' (399K)',
 ' (225K)',
 ' (79K)',
 ' (186K)',
 ' (5.9K)',
 ' (2.3M)',
 ' (24K)',
 ' (69K)',
 ' (777K)',
 ' (3.7K)',
 ' (16K)',
 ' (221K)',
 ' (220K)',
 ' (2.2M)',
 ' (27K)',
 ' (486K)',
 ' (1.4M)',
 ' (227K)',
 ' (345K)',
 ' (50K)',
 ' (479K)',
 ' (156K)',
 ' (1.1M)',
 ' (488K)',
 ' (250K)',
 ' (76K)',
 ' (148K)',
 ' (610K)',
 ' (112K)',
 ' (98K)',
 ' (127K)',
 ' (663K)',
 ' (165K)',
 ' (4.4K)',
 ' (521K)',
 ' (290K)',
 ' (723K)',
 ' (37K)',
 ' (71K)',
 ' (17K)',
 ' (76K)',
 ' (876K)',
 ' (122K)',
 ' (659K)',
 ' (529K)',
 ' (109K)',
 ' (544K)',
 ' (27K)',
 ' (181K)',
 ' (128K)',
 ' (490K)',
 ' (26K)',
 ' (660K)',
 ' (1.1M)',
 ' (734K)',
 ' (209K)',
 ' (49K)',
 ' (2K)',
 ' (9.3K)',
 ' (40K)',
 ' (356K)',
 ' (43K)',
 ' (280K)',
 ' (647K)',
 ' (589K)',
 ' (244K)',
 ' (357K)',
 ' (92K)',
 ' (426K)',
 ' (601K)',
 ' (346K)',
 ' (178K)',
 ' (248K)',
 ' (143K)',
 ' (49K)',
 ' (126K)',
 ' (370K)',
 ' (790)',
 ' (8.7K)',
 ' (259K)',
 ' (254K)',
 ' (382K)',
 ' (61K)',
 ' (359K)',
 ' (213K)',
 ' (10K)',
 ' (218K)',
 ' (116K)',
 ' (64K)',
 ' (534K)',
 ' (326K)',
 ' (532)',
 ' (252K)',
 ' (12K)',
 ' (73K)',
 ' (5.7K)',
 ' (575K)']

In [174]:
len(vote)

98

In [175]:
rating = []
try:
    for i in driver7.find_elements(By.XPATH,'//span[@class="ipc-rating-star ipc-rating-star--base ipc-rating-star--imdb ratingGroup--imdb-rating"]'):
        rating.append(i.text)
except NoSuchElementException as e:
        rating.append("-")
rating

['8.7\n (682K)',
 '8.4\n (399K)',
 '8.6\n (225K)',
 '3.5\n (79K)',
 '7.4\n (186K)',
 '7.6\n (5.9K)',
 '9.2\n (2.3M)',
 '7.8\n (24K)',
 '7.6\n (69K)',
 '8.6\n (777K)',
 '7.1\n (3.7K)',
 '6.1\n (16K)',
 '8.1\n (221K)',
 '8.4\n (220K)',
 '9.5\n (2.2M)',
 '6.9\n (27K)',
 '8.4\n (486K)',
 '8.7\n (1.4M)',
 '8.7\n (227K)',
 '7.6\n (345K)',
 '8.2\n (50K)',
 '9.2\n (479K)',
 '8.6\n (156K)',
 '8.1\n (1.1M)',
 '8.4\n (488K)',
 '8.6\n (250K)',
 '8.0\n (76K)',
 '8.7\n (148K)',
 '9.1\n (610K)',
 '7.7\n (112K)',
 '7.7\n (98K)',
 '8.1\n (127K)',
 '8.9\n (663K)',
 '7.8\n (165K)',
 '6.7\n (4.4K)',
 '8.7\n (521K)',
 '8.5\n (290K)',
 '9.0\n (723K)',
 '7.8\n (37K)',
 '7.7\n (71K)',
 '8.5\n (17K)',
 '7.7\n (76K)',
 '8.1\n (876K)',
 '8.1\n (122K)',
 '9.0\n (659K)',
 '9.1\n (529K)',
 '8.4\n (109K)',
 '8.7\n (544K)',
 '6.4\n (27K)',
 '8.4\n (181K)',
 '7.5\n (128K)',
 '8.5\n (490K)',
 '7.3\n (26K)',
 '8.8\n (660K)',
 '8.9\n (1.1M)',
 '8.3\n (734K)',
 '8.7\n (209K)',
 '7.9\n (49K)',
 '6.5\n (2K)',
 '7.2\n (9.3K)',
 '7.9\n (40K)',
 '8.2\n (356K)',
 '8.2\n (43K)',
 '8.8\n (280K)',
 '8.7\n (647K)',
 '8.5\n (589K)',
 '9.0\n (244K)',
 '8.8\n (357K)',
 '8.1\n (92K)',
 '8.9\n (426K)',
 '8.3\n (601K)',
 '8.0\n (346K)',
 '7.8\n (178K)',
 '8.3\n (248K)',
 '8.2\n (143K)',
 '9.2\n (49K)',
 '7.8\n (126K)',
 '8.4\n (370K)',
 '6.3\n (790)',
 '8.5\n (8.7K)',
 '8.6\n (259K)',
 '8.8\n (254K)',
 '9.3\n (382K)',
 '7.5\n (61K)',
 '7.0\n (359K)',
 '8.0\n (213K)',
 '7.0\n (10K)',
 '8.1\n (218K)',
 '8.0\n (116K)',
 '8.1\n (64K)',
 '9.4\n (534K)',
 '8.6\n (326K)',
 '5.8\n (532)',
 '8.6\n (252K)',
 '7.5\n (12K)',
 '8.0\n (73K)',
 '8.4\n (5.7K)',
 '8.0\n (575K)']

8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You
have to find the following details:
    
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

In [208]:
driver8 = webdriver.Chrome()

In [209]:
driver8.get("https://archive.ics.uci.edu/")

In [210]:
viewdataset = driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
viewdataset.click()

In [199]:
set_url =[]
while len(set_url)< 665:
    for i in driver8.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]'):
        set_url.append(i.get_attribute("href"))
    nxt_button = driver8.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
    nxt_button.click()

ElementClickInterceptedException: Message: element click intercepted: Element <button class="btn-primary btn-sm btn" aria-label="Next Page" disabled="">...</button> is not clickable at point (1205, 698). Other element would receive the click: <div class="btn-group">...</div>
  (Session info: chrome=126.0.6478.127)
Stacktrace:
0   chromedriver                        0x000000010112aa80 chromedriver + 4385408
1   chromedriver                        0x000000010112338c chromedriver + 4354956
2   chromedriver                        0x0000000100d40b0c chromedriver + 281356
3   chromedriver                        0x0000000100d88ce0 chromedriver + 576736
4   chromedriver                        0x0000000100d87284 chromedriver + 569988
5   chromedriver                        0x0000000100d85414 chromedriver + 562196
6   chromedriver                        0x0000000100d845b0 chromedriver + 558512
7   chromedriver                        0x0000000100d79cfc chromedriver + 515324
8   chromedriver                        0x0000000100d79734 chromedriver + 513844
9   chromedriver                        0x0000000100dbbd24 chromedriver + 785700
10  chromedriver                        0x0000000100d77eec chromedriver + 507628
11  chromedriver                        0x0000000100d788c4 chromedriver + 510148
12  chromedriver                        0x00000001010f243c chromedriver + 4154428
13  chromedriver                        0x00000001010f6ea0 chromedriver + 4173472
14  chromedriver                        0x00000001010d7ff8 chromedriver + 4046840
15  chromedriver                        0x00000001010f778c chromedriver + 4175756
16  chromedriver                        0x00000001010cafb8 chromedriver + 3993528
17  chromedriver                        0x000000010111521c chromedriver + 4297244
18  chromedriver                        0x0000000101115398 chromedriver + 4297624
19  chromedriver                        0x0000000101122f84 chromedriver + 4353924
20  libsystem_pthread.dylib             0x00000001875f2f94 _pthread_start + 136
21  libsystem_pthread.dylib             0x00000001875edd34 thread_start + 8

In [200]:
len(set_url)

660

In [214]:
Datatype =[]
Dataset_name = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attribute = []
Year = []
for i in set_url[:20]:
    driver8.get(i)
    try:
        Datasetname_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/div/h1")
        Dataset_name.append(Datasetname_tag.text)
    except NoSuchElementException as e:
        Dataset_name.append("--")
    try:
        Datatype_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[1]/h1")
        Datatype.append(Datatype_tag.text)
    except NoSuchElementException as e:
        Datatype.append("--")
    try:
        Task_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p")
        Task.append(Task_tag.text)
    except NoSuchElementException as e:
        Task.append("--")
    try:
        Attribute_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[4]/p")
        Attribute_type.append(Attribute_tag.text)
    except NoSuchElementException as e:
        Attribute_type.append("--")
    try:
        No_of_instances_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[5]/p")
        No_of_instances.append(No_of_instances_tag.text)
    except NoSuchElementException as e:
        No_of_instances.append("--")
    try:
        No_of_attribute_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[6]/p")
        No_of_attribute.append(No_of_attribute_tag.text)
    except NoSuchElementException as e:
        No_of_attribute.append("--")
    try:
        Year_tag=driver8.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/h2")
        Year.append(Year_tag.text)
    except NoSuchElementException as e:
        Year.append("--")

In [215]:
len(Dataset_name)

20

In [216]:
df8 = pd.DataFrame({"Datatype":Datatype,"Dataset name":Dataset_name,"Task":Task,"Attribute type":Attribute_type,"No_of_instances":No_of_instances,"No_of_attribute":No_of_attribute,"Year":Year})

In [217]:
df8

,Datatype,Dataset name,Task,Attribute type,No_of_instances,No_of_attribute,Year
0,Dataset Characteristics,Diabetes,Classification,"Categorical, Integer",1,20,--
1,Dataset Characteristics,Car Evaluation,Classification,Categorical,1728,6,Donated on 5/31/1997
2,Dataset Characteristics,Student Performance,"Classification, Regression",Integer,649,30,Donated on 11/26/2014
3,Dataset Characteristics,Abalone,"Classification, Regression","Categorical, Integer, Real",4177,8,Donated on 11/30/1995
4,Dataset Characteristics,Mushroom,Classification,Categorical,8124,22,Donated on 4/26/1987
5,Dataset Characteristics,Online Retail,"Classification, Clustering","Integer, Real",541909,6,Donated on 11/5/2015
6,Dataset Characteristics,Statlog (German Credit Data),Classification,"Categorical, Integer",1000,20,Donated on 11/16/1994
7,Dataset Characteristics,Automobile,Regression,"Categorical, Integer, Real",205,25,Donated on 5/18/1987
8,Dataset Characteristics,Predict Students' Dropout and Academic Success,Classification,"Real, Categorical, Integer",4424,36,Donated on 12/12/2021
9,Dataset Characteristics,Census Income,Classification,"Categorical, Integer",48842,14,Donated on 4/30/1996
10,Dataset Characteristics,Diabetes,Classification,"Categorical, Integer",1,20,--
11,Dataset Characteristics,Car Evaluation,Classification,Categorical,1728,6,Donated on 5/31/1997
12,Dataset Characteristics,Student Performance,"Classification, Regression",Integer,649,30,Donated on 11/26/2014
13,Dataset Characteristics,Abalone,"Classification, Regression","Categorical, Integer, Real",4177,8,Donated on 11/30/1995
14,Dataset Characteristics,Mushroom,Classification,Categorical,8124,22,Donated on 4/26/1987
15,Dataset Characteristics,Online Retail,"Classification, Clustering","Integer, Real",541909,6,Donated on 11/5/2015
16,Dataset Characteristics,Statlog (German Credit Data),Classification,"Categorical, Integer",1000,20,Donated on 11/16/1994
17,Dataset Characteristics,Automobile,Regression,"Categorical, Integer, Real",205,25,Donated on 5/18/1987
18,Dataset Characteristics,Predict Students' Dropout and Academic Success,Classification,"Real, Categorical, Integer",4424,36,Donated on 12/12/2021
19,Dataset Characteristics,Census Income,Classification,"Categorical, Integer",48842,14,Donated on 4/30/1996